name: Continious Integrations

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Unit Testing
        run: mvn verify

