name: Deploy to ECS - Beta

on:
  repository_dispatch:
    types: [beta]

env:
  ECR_REPO: 495425317860.dkr.ecr.eu-west-1.amazonaws.com/github-action-trial
  AWS_DEFAULT_REGION: eu-west-1
  VERSION: $(git rev-parse --short HEAD)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo payload
        run: |
          echo "field: ${{ github.event.client_payload.foo }}"